### ISSUE TITLE
amrfinder_update: command not found

### ISSUE THREAD

**Issue by raphenya** [pha4ge/hAMRonization-workflow#14]
I got amrfinder_update: command not found when following the installation instructions.
I ran: `bash get_dbs.sh`. I'm guessing `amrfinder` is installed via execution.

**Comment by simonhtausch** [comment]
Actually the get_dbs.sh has several dependencies which are only installed on execution of the snakemake pipeline. Since that depends on these dbs to be installed, it's a hen and egg problem at the moment. 
The non-standard dependencies are:
- rgi
- bwa
- kma
- ariba
- ncbi-amrfinderplus
- blast
- groot=0.8.3=1 (the latest conda package seems to have changed CLI options)
- curl

We might just change the dependency structure from several envs for each rule to one general env and install that via a installation script beforehand so we don't need to install them redundantly.

For now you can just install all of these into the hamronization conda env (`conda install rgi bwa kma ariba ncbi-amrfinderplus blast curl groot=0.8.3=1 `) to fix the problem, but we'll  look into it.

**Comment by simonhtausch** [comment]
I've added a yaml file for the basic dependencies needed for the installation. Building the dbs should work now if you build the basic environment using `conda env create -n hamronization --file envs/hamronization.yaml`.

**Comment by fmaguire** [comment]
@raphenya look at the `run_test.sh` script and it shows all the commands that need run on a fresh system.
